[0m[[0m[31merror[0m] [0m[0mjava.lang.RuntimeException: java.lang.RuntimeException: java.net.ConnectException[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.ollama.OllamaEmbeddingModel.embedAll(OllamaEmbeddingModel.java:66)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)[0m
[0m[[0m[31merror[0m] [0m[0m	at it.unibo.basics.EmbeddingBaseExample.main(EmbeddingBaseExample.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:580)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:144)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:94)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2044)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1983)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:1583)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.lang.RuntimeException: java.net.ConnectException[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.http.client.jdk.JdkHttpClient.execute(JdkHttpClient.java:52)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.http.client.log.LoggingHttpClient.execute(LoggingHttpClient.java:39)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.ollama.OllamaClient.embed(OllamaClient.java:190)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.ollama.OllamaEmbeddingModel.lambda$embedAll$0(OllamaEmbeddingModel.java:66)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.ollama.OllamaEmbeddingModel.embedAll(OllamaEmbeddingModel.java:66)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)[0m
[0m[[0m[31merror[0m] [0m[0m	at it.unibo.basics.EmbeddingBaseExample.main(EmbeddingBaseExample.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:580)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:144)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:94)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2044)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1983)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:1583)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.net.ConnectException[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:952)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.http.client.jdk.JdkHttpClient.execute(JdkHttpClient.java:44)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.http.client.log.LoggingHttpClient.execute(LoggingHttpClient.java:39)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.ollama.OllamaClient.embed(OllamaClient.java:190)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.ollama.OllamaEmbeddingModel.lambda$embedAll$0(OllamaEmbeddingModel.java:66)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.ollama.OllamaEmbeddingModel.embedAll(OllamaEmbeddingModel.java:66)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)[0m
[0m[[0m[31merror[0m] [0m[0m	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)[0m
[0m[[0m[31merror[0m] [0m[0m	at it.unibo.basics.EmbeddingBaseExample.main(EmbeddingBaseExample.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:580)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:144)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:94)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2044)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1983)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:1583)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.net.ConnectException[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1041)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:1583)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.nio.channels.ClosedChannelException[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:202)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:786)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:874)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:1583)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) java.lang.RuntimeException: java.net.ConnectException[0m
